services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: petmedtrack-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER:  guest
      RABBITMQ_DEFAULT_PASS:  guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq


  app:
    image: petmedtrack:latest
    container_name: petmedtrack-app
    restart: unless-stopped
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        JWT_SECRET: ${JWT_SECRET}
        JWT_EXPIRATION: 86400000
        MAIL_USERNAME: ${MAIL_USERNAME}
        MAIL_PASSWORD: ${MAIL_PASSWORD}
        SPRING_DATASOURCE_URL: jdbc:sqlserver://host.docker.internal:1433;databaseName=petmedtrack;encrypt=true;trustServerCertificate=true
        SPRING_RABBITMQ_HOST: rabbitmq
        SPRING_RABBITMQ_PORT: 5672
        SPRING_RABBITMQ_USERNAME: guest
        SPRING_RABBITMQ_PASSWORD: guest


volumes:
  rabbitmq-data:
